Blog.IdentityServer/Controllers/Client/ClientsManagerController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;
using Blog.Core.Common.Helper;
using Blog.IdentityServer.Models;
using IdentityServer4;
using IdentityServer4.EntityFramework.DbContexts;
using IdentityServer4.EntityFramework.Mappers;
using IdentityServer4.Models;
using Microsoft.AspNetCore.Authorization;
using Microsoft.AspNetCore.Http;
using Microsoft.AspNetCore.Mvc;
using Microsoft.EntityFrameworkCore;
using static IdentityModel.OidcConstants;

namespace Blog.IdentityServer.Controllers.Client
{
    [Route("[controller]/[action]")]
    [ApiController]
    public class ClientsManagerController : Controller
    {
        private readonly ConfigurationDbContext _configurationDbContext;

        public ClientsManagerController(ConfigurationDbContext configurationDbContext)
        {
            _configurationDbContext = configurationDbContext;
        }

        /// <summary>
        /// 数据列表页
        /// </summary>
        /// <returns></returns>
        [HttpGet]
        [Authorize]
        public async Task<IActionResult> Index()
        {
            return View(await _configurationDbContext.Clients
                .Include(d => d.AllowedGrantTypes)
                .Include(d => d.AllowedScopes)
                .Include(d => d.AllowedCorsOrigins)
                .Include(d => d.RedirectUris)
                .Include(d => d.PostLogoutRedirectUris)
                .ToListAsync());
        }

        /// <summary>
        /// 数据修改页
        /// </summary>
        /// <param name="id"></param>
        /// <returns></returns>
        [HttpGet]
        [Authorize(Policy = "SuperAdmin")]
        public IActionResult CreateOrEdit(int id)
        {
            ViewBag.ClientId = id;
            return View();
        }


        [HttpGet]
        [Authorize(Policy = "SuperAdmin")]
        public async Task<MessageModel<ClientDto>> GetDataById(int id = 0)
        {
            var model = (await _configurationDbContext.Clients
                .Include(d => d.AllowedGrantTypes)
                .Include(d => d.AllowedScopes)
                .Include(d => d.AllowedCorsOrigins)
                .Include(d => d.RedirectUris)
                .Include(d => d.PostLogoutRedirectUris)
                .Include(d => d.ClientSecrets)
                .ToListAsync()).FirstOrDefault(d => d.Id == id).ToModel();

            var clientDto = new ClientDto();
            if (model != null)
            {
                clientDto = new ClientDto()
                {
                    ClientId = model?.ClientId,
                    ClientName = model?.ClientName,
                    Description = model?.Description,
                    AllowAccessTokensViaBrowser = (model?.AllowAccessTokensViaBrowser).ObjToString(),
                    AllowedCorsOrigins = string.Join(",", model?.AllowedCorsOrigins),
                    AllowedGrantTypes = string.Join(",", model?.AllowedGrantTypes),
                    AllowedScopes = string.Join(",", model?.AllowedScopes),
                    PostLogoutRedirectUris = string.Join(",", model?.PostLogoutRedirectUris),
                    RedirectUris = string.Join(",", model?.RedirectUris),
                    ClientSecrets = string.Join(",", model?.ClientSecrets.Select(d => d.Value)),
                };
            }

            return new MessageModel<ClientDto>()
            {
                success = true,
                msg = "获取成功",
                response = clientDto
            };
        }

        [HttpPost]
        [Authorize(Policy = "SuperAdmin")]
        public async Task<MessageModel<string>> SaveData(ClientDto request)
        {
            if (request != null && request.id == 0)
            {
                IdentityServer4.Models.Client client = new IdentityServer4.Models.Client()
                {
                    ClientId = request?.ClientId,
                    ClientName = request?.ClientName,
                    Description = request?.Description,
                    AllowAccessTokensViaBrowser = (request?.AllowAccessTokensViaBrowser).ObjToBool(),
                    AllowedCorsOrigins = request?.AllowedCorsOrigins?.Split(","),
                    AllowedGrantTypes = request?.AllowedGrantTypes?.Split(","),
                    AllowedScopes = request?.AllowedScopes?.Split(","),
                    PostLogoutRedirectUris = request?.PostLogoutRedirectUris?.Split(","),
                    RedirectUris = request?.RedirectUris?.Split(","),
                };

                if (!string.IsNullOrEmpty(request.ClientSecrets))
                {
                    client.ClientSecrets = new List<Secret>() { new Secret(request.ClientSecrets.Sha256()) };
                }

                var result = (await _configurationDbContext.Clients.AddAsync(client.ToEntity()));
                await _configurationDbContext.SaveChangesAsync();
            }

            if (request != null && request.id > 0)
            {

                var modelEF = (await _configurationDbContext.Clients
                    .Include(d => d.AllowedGrantTypes)
                    .Include(d => d.AllowedScopes)
                    .Include(d => d.AllowedCorsOrigins)
                    .Include(d => d.RedirectUris)
                    .Include(d => d.PostLogoutRedirectUris)
                    .ToListAsync()).FirstOrDefault(d => d.Id == request.id);

                modelEF.ClientId = request?.ClientId;
                modelEF.ClientName = request?.ClientName;
                modelEF.Description = request?.Description;
                modelEF.AllowAccessTokensViaBrowser = (request?.AllowAccessTokensViaBrowser).ObjToBool();

                var AllowedCorsOrigins = new List<IdentityServer4.EntityFramework.Entities.ClientCorsOrigin>();
                if (!string.IsNullOrEmpty(request?.AllowedCorsOrigins))
                {
                    request?.AllowedCorsOrigins.Split(",").Where(s => s != "" && s != null).ToList().ForEach(s =>
                               {
                                   AllowedCorsOrigins.Add(new IdentityServer4.EntityFramework.Entities.ClientCorsOrigin()
                                   {
                                       Client = modelEF,
                                       ClientId = modelEF.Id,
                                       Origin = s
                                   });
                               });
                    modelEF.AllowedCorsOrigins = AllowedCorsOrigins;
                }



                var AllowedGrantTypes = new List<IdentityServer4.EntityFramework.Entities.ClientGrantType>();
                if (!string.IsNullOrEmpty(request?.AllowedGrantTypes))
                {
                    request?.AllowedGrantTypes.Split(",").Where(s => s != "" && s != null).ToList().ForEach(s =>
                    {
                        AllowedGrantTypes.Add(new IdentityServer4.EntityFramework.Entities.ClientGrantType()
                        {
                            Client = modelEF,
                            ClientId = modelEF.Id,
                            GrantType = s
                        });
                    });
                    modelEF.AllowedGrantTypes = AllowedGrantTypes;
                }



                var AllowedScopes = new List<IdentityServer4.EntityFramework.Entities.ClientScope>();
                if (!string.IsNullOrEmpty(request?.AllowedScopes))
                {
                    request?.AllowedScopes.Split(",").Where(s => s != "" && s != null).ToList().ForEach(s =>
                    {
                        AllowedScopes.Add(new IdentityServer4.EntityFramework.Entities.ClientScope()
                        {
                            Client = modelEF,
                            ClientId = modelEF.Id,
                            Scope = s
                        });
                    });
                    modelEF.AllowedScopes = AllowedScopes;
                }


                var PostLogoutRedirectUris = new List<IdentityServer4.EntityFramework.Entities.ClientPostLogoutRedirectUri>();
                if (!string.IsNullOrEmpty(request?.PostLogoutRedirectUris))
                {
                    request?.PostLogoutRedirectUris.Split(",").Where(s => s != "" && s != null).ToList().ForEach(s =>
                    {
                        PostLogoutRedirectUris.Add(new IdentityServer4.EntityFramework.Entities.ClientPostLogoutRedirectUri()
                        {
                            Client = modelEF,
                            ClientId = modelEF.Id,
                            PostLogoutRedirectUri = s
                        });
                    });
                    modelEF.PostLogoutRedirectUris = PostLogoutRedirectUris;
                }


                var RedirectUris = new List<IdentityServer4.EntityFramework.Entities.ClientRedirectUri>();
                if (!string.IsNullOrEmpty(request?.RedirectUris))
                {
                    request?.RedirectUris.Split(",").Where(s => s != "" && s != null).ToList().ForEach(s =>
                    {
                        RedirectUris.Add(new IdentityServer4.EntityFramework.Entities.ClientRedirectUri()
                        {
                            Client = modelEF,
                            ClientId = modelEF.Id,
                            RedirectUri = s
                        });
                    });
                    modelEF.RedirectUris = RedirectUris;
                }

                var result = (_configurationDbContext.Clients.Update(modelEF));
                await _configurationDbContext.SaveChangesAsync();
            }


            return new MessageModel<string>()
            {
                success = true,
                msg = "添加成功",
            };
        }
    }
}

Blog.IdentityServer/Views/Shared/Redirect.cshtml
@model RedirectViewModel

<h1>You are now being returned to the application.</h1>
<p>Once complete, you may close this tab</p>

<meta http-equiv="refresh" content="0;url=@Model.RedirectUrl" data-url="@Model.RedirectUrl">
<script src="~/js/signin-redirect.js"></script>

Blog.IdentityServer/Views/Shared/_Layout.cshtml
@using IdentityServer4.Extensions
@{
    string name = null;
    if (!true.Equals(ViewData["signed-out"]))
    {
        name = Context.User?.GetDisplayName();
    }
}
<!DOCTYPE html>
<html>
<head>
    <meta charset="utf-8" />
    <meta http-equiv="X-UA-Compatible" content="IE=edge">
    <meta name="viewport" content="width=device-width, initial-scale=1.0" />
    <title>IdentityServer4</title>
    <link rel="icon" type="image/x-icon" href="~/favicon.ico" />
    <link rel="shortcut icon" type="image/x-icon" href="~/favicon.ico" />
    @*<link rel="stylesheet" href="~/lib/bootstrap/css/bootstrap.css" />
        <link rel="stylesheet" href="~/css/site.css" />*@


    <link href="~/css/bundle.min.css" rel="stylesheet" />
    <link href="~/css/web.css" rel="stylesheet" />

    <script src="~/lib/jquery/jquery.min.js"></script>
    @*<script src="~/lib/bootstrap/js/bootstrap.min.js"></script>*@
    <script src="~/js/bundle.min.js"></script>
    <script src="~/js/showTip.js"></script>

</head>
<body>
    @if (!string.IsNullOrWhiteSpace(name))
    {
        <div class="navbar navbar-inverse navbar-fixed-top">
            <div class="container-fluid">
                @*<div class="navbar-header">
                        <button type="button" class="navbar-toggle collapsed" data-toggle="collapse" data-target="#bs-example-navbar-collapse-1" aria-expanded="false">
                            <span class="sr-only">Toggle navigation</span>
                            <span class="icon-bar"></span>
                            <span class="icon-bar"></span>
                            <span class="icon-bar"></span>
                        </button>
                        <a href="~/">
                            <span class="navbar-brand">
                                <img src="~/icon.png" class="icon-banner">
                                Blog.Idp
                            </span>
                        </a>
                    </div>*@


                <div class="width100p menu width100% d-flex flex-column flex-md-row align-items-center p-3 px-md-4 mb-3 bg-white border-bottom box-shadow">
                    <!--Site name -->
                    <h3 class="menu-logo my-0 mr-md-auto font-weight-normal"><a class="logo" href="/">Blog.Idp</a></h3>
                    <!--Menu item -->
                    <!--Menu item -->
                    <!--Menu item -->
                    <div class="menu-item my-2 my-md-0 mr-md-3 dropdown">
                        <button type="button" class="btn btn-primary dropdown-toggle" data-toggle="dropdown">
                            设置 - @name
                        </button>
                        <div class="dropdown-menu">
                            <a class="dropdown-item" href="/Account/users">用户</a>
                            <a class="dropdown-item" href="/ClientsManager/index">客户端</a>
                            <a class="dropdown-item" href="/ApiResourcesManager/index">资源api</a>
                            <a class="dropdown-item" href="/Account/forgot-password">更改密码</a>
                            <a class="dropdown-item" href="/Grants">授权</a>
                            <a class="dropdown-item" href="/Account/My">个人中心</a>
                        </div>
                    </div>
                    <a class="menu-item my-2 btn btn-outline-primary" href="/Account/Logout">注销</a>

                    <!--Menu button - show in < MD -->
                    <a class="my-2 btn btn-outline-primary menu-button" href="#">
                        <span class="oi oi-menu" title="menu" aria-hidden="true"></span> 菜单
                    </a>
                </div>


                @*<li class="dropdown">
                        <a href="#" class="dropdown-toggle" data-toggle="dropdown">@name <b class="caret"></b></a>
                        <ul class="dropdown-menu">
                            <li><a asp-action="forgot-password" asp-controller="Account">修改密码</a></li>
                            <li><a asp-action="Logout" asp-controller="Account">退出登录</a></li>
                        </ul>
                    </li>

                    <li class="dropdown">
                        <a href="#" class="dropdown-toggle" data-toggle="dropdown">用户管理 <b class="caret"></b></a>
                        <ul class="dropdown-menu">
                            <li><a asp-action="users" asp-controller="Account">用户</a></li>
                            <li><a asp-action="roles" asp-controller="Account">角色</a></li>
                        </ul>
                    </li>
                    <li class="dropdown">
                        <a href="#" class="dropdown-toggle" data-toggle="dropdown">资源管理 <b class="caret"></b></a>
                        <ul class="dropdown-menu">
                            <li><a asp-action="index" asp-controller="ClientsManager">客户端</a></li>
                            <li><a asp-action="index" asp-controller="ApiResourcesManager">资源api</a></li>
                        </ul>
                    </li>*@




            </div>
        </div>
    }
    <div class="content-bd">
        @RenderBody()
    </div>
    @RenderSection("scripts", required: false)
</body>
</html>

Blog.IdentityServer/Views/Shared/_ScopeListItem.cshtml
@model ScopeViewModel

<li class="list-group-item">
    <label>
        <input class="consent-scopecheck"
               type="checkbox"
               name="ScopesConsented"
               id="scopes_@Model.Value"
               value="@Model.Value"
               checked="@Model.Checked"
               disabled="@Model.Required" />
        @if (Model.Required)
        {
            <input type="hidden"
                   name="ScopesConsented"
                   value="@Model.Value" />
        }
        <strong>@Model.DisplayName</strong>
        @if (Model.Emphasize)
        {
            <span class="glyphicon glyphicon-exclamation-sign"></span>
        }
    </label>
    @if (Model.Required)
    {
        <span><em>(required)</em></span>
    }
    @if (Model.Description != null)
    {
        <div class="consent-description">
            <label for="scopes_@Model.Value">@Model.Description</label>
        </div>
    }
</li>

Blog.IdentityServer/Views/Shared/_ValidationSummary.cshtml
@if (ViewContext.ModelState.IsValid == false)
{
    <div class="alert alert-danger">
        <strong>Error</strong>
        <div asp-validation-summary="All" class="danger"></div>
    </div>
}